// Dữ liệu mẫu cho khách hàng
export const mockCustomers = [
  {
    id: "KH001",
    name: "Nguyễn Văn A",
    phone: "0901234567",
    email: "nguyenvana@example.com",
    address: "123 Đường Lê Lợi, Quận 1, TP.HCM",
    type: "VIP",
    createdAt: "01/03/2023",
  },
  {
    id: "KH002",
    name: "Trần Thị B",
    phone: "0912345678",
    email: "tranthib@example.com",
    address: "456 Đường Nguyễn Huệ, Quận 1, TP.HCM",
    type: "Tiềm năng",
    createdAt: "15/03/2023",
  },
  {
    id: "KH003",
    name: "Lê Văn C",
    phone: "0923456789",
    email: "levanc@example.com",
    address: "789 Đường Cách Mạng Tháng 8, Quận 3, TP.HCM",
    type: "Mới",
    createdAt: "10/04/2023",
  },
  {
    id: "KH004",
    name: "Phạm Thị D",
    phone: "0934567890",
    email: "phamthid@example.com",
    address: "101 Đường Võ Văn Tần, Quận 3, TP.HCM",
    type: "Cũ",
    createdAt: "05/01/2023",
  },
  {
    id: "KH005",
    name: "Hoàng Văn E",
    phone: "0945678901",
    email: "hoangvane@example.com",
    address: "202 Đường Điện Biên Phủ, Quận Bình Thạnh, TP.HCM",
    type: "VIP",
    createdAt: "20/02/2023",
  },
  {
    id: "KH006",
    name: "Ngô Thị F",
    phone: "0956789012",
    email: "ngothif@example.com",
    address: "303 Đường Nguyễn Đình Chiểu, Quận 3, TP.HCM",
    type: "Tiềm năng",
    createdAt: "15/05/2023",
  },
]

// Dữ liệu mẫu cho đơn hàng
export const mockOrders = [
  {
    id: "DH001",
    customerId: "KH001",
    customerName: "Nguyễn Văn A",
    date: "10/05/2023",
    total: 25000000,
    status: "Thành công",
  },
  {
    id: "DH002",
    customerId: "KH002",
    customerName: "Trần Thị B",
    date: "12/05/2023",
    total: 18000000,
    status: "Thành công",
  },
  {
    id: "DH003",
    customerId: "KH003",
    customerName: "Lê Văn C",
    date: "15/05/2023",
    total: 32000000,
    status: "Đang xử lý",
  },
  {
    id: "DH004",
    customerId: "KH004",
    customerName: "Phạm Thị D",
    date: "18/05/2023",
    total: 15000000,
    status: "Thành công",
  },
  {
    id: "DH005",
    customerId: "KH005",
    customerName: "Hoàng Văn E",
    date: "20/05/2023",
    total: 45000000,
    status: "Đang xử lý",
  },
  {
    id: "DH006",
    customerId: "KH001",
    customerName: "Nguyễn Văn A",
    date: "22/05/2023",
    total: 28000000,
    status: "Thành công",
  },
  {
    id: "DH007",
    customerId: "KH006",
    customerName: "Ngô Thị F",
    date: "25/05/2023",
    total: 22000000,
    status: "Đang xử lý",
  },
]

// Dữ liệu mẫu cho dịch vụ
export const mockServices = [
  {
    id: "DV001",
    name: "Bảo hành sản phẩm",
    description: "Dịch vụ bảo hành sản phẩm trong thời gian 12 tháng kể từ ngày mua",
  },
  {
    id: "DV002",
    name: "Sửa chữa điện thoại",
    description: "Dịch vụ sửa chữa điện thoại với chi phí hợp lý và thời gian nhanh chóng",
  },
  {
    id: "DV003",
    name: "Tư vấn sản phẩm",
    description: "Dịch vụ tư vấn sản phẩm phù hợp với nhu cầu của khách hàng",
  },
  {
    id: "DV004",
    name: "Giao hàng tận nơi",
    description: "Dịch vụ giao hàng tận nơi trong vòng 24 giờ sau khi đặt hàng",
  },
  {
    id: "DV005",
    name: "Hỗ trợ kỹ thuật",
    description: "Dịch vụ hỗ trợ kỹ thuật 24/7 qua điện thoại hoặc email",
  },
]

// Dữ liệu mẫu cho đánh giá dịch vụ
export const mockRatings = [
  {
    id: "DG001",
    customerId: "KH001",
    customerName: "Nguyễn Văn A",
    serviceId: "DV001",
    serviceName: "Bảo hành sản phẩm",
    serviceRating: 5,
    staffRating: 5,
    description: "Dịch vụ rất tốt, nhân viên nhiệt tình",
    date: "15/05/2023",
  },
  {
    id: "DG002",
    customerId: "KH002",
    customerName: "Trần Thị B",
    serviceId: "DV002",
    serviceName: "Sửa chữa điện thoại",
    serviceRating: 4,
    staffRating: 5,
    description: "Sửa chữa nhanh chóng, nhân viên thân thiện",
    date: "16/05/2023",
  },
  {
    id: "DG003",
    customerId: "KH003",
    customerName: "Lê Văn C",
    serviceId: "DV003",
    serviceName: "Tư vấn sản phẩm",
    serviceRating: 3,
    staffRating: 4,
    description: "Tư vấn khá tốt, nhưng còn một số thông tin chưa rõ ràng",
    date: "17/05/2023",
  },
  {
    id: "DG004",
    customerId: "KH004",
    customerName: "Phạm Thị D",
    serviceId: "DV004",
    serviceName: "Giao hàng tận nơi",
    serviceRating: 5,
    staffRating: 4,
    description: "Giao hàng đúng hẹn, nhân viên giao hàng lịch sự",
    date: "18/05/2023",
  },
  {
    id: "DG005",
    customerId: "KH005",
    customerName: "Hoàng Văn E",
    serviceId: "DV005",
    serviceName: "Hỗ trợ kỹ thuật",
    serviceRating: 4,
    staffRating: 3,
    description: "Hỗ trợ kỹ thuật tốt, nhưng thời gian chờ hơi lâu",
    date: "19/05/2023",
  },
]

// Dữ liệu mẫu cho lịch sử liên lạc
export const mockContacts = [
  {
    id: "LL001",
    customerId: "KH001",
    customerName: "Nguyễn Văn A",
    type: "Gọi điện",
    date: "10/05/2023",
    result: "Thành công",
    description: "Khách đồng ý đặt iPhone 15",
    staffRating: 5,
  },
  {
    id: "LL002",
    customerId: "KH002",
    customerName: "Trần Thị B",
    type: "Email",
    date: "11/05/2023",
    result: "Thành công",
    description: "Khách hỏi về chính sách bảo hành",
    staffRating: 4,
  },
  {
    id: "LL003",
    customerId: "KH003",
    customerName: "Lê Văn C",
    type: "Chat",
    date: "12/05/2023",
    result: "Không thành công",
    description: "Hẹn gọi lại vào tuần sau ở cửa hàng",
    staffRating: 3,
  },
  {
    id: "LL004",
    customerId: "KH004",
    customerName: "Phạm Thị D",
    type: "Gọi điện",
    date: "13/05/2023",
    result: "Thành công",
    description: "Khách đồng ý mua Samsung Galaxy S23",
    staffRating: 5,
  },
  {
    id: "LL005",
    customerId: "KH005",
    customerName: "Hoàng Văn E",
    type: "Chat",
    date: "14/05/2023",
    result: "Thành công",
    description: "Khách hỏi về khuyến mãi hiện tại của cửa hàng",
    staffRating: 4,
  },
]
